swagger: '2.0'
info:
  title: Sunglasses.io API
  description: Sunglasses.io web store API
  version: 0.0.1
host: localhost:8080
schemes:
  - https
basePath: /api
produces:
  - application/json
paths:
  /products:
    get:
      summary: Product Types
      description: |
        Returns an array of available product types.
      parameters:
        - name: product
          in: query
          description: Product query
          required: true
          type: string
          format: string
      tags:
        - Products
      responses:
        '200':
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /brands:
    get:
      summary: Brand Names
      description: |
        Returns an array of available brands.
      parameters:
        - name: brand
          in: query
          description: An array of brands
          required: true
          type: string
          format: string
      tags:
        - Brands
      responses:
        '200':
          description: An array of brands
          schema:
            type: array
            items:
              $ref: '#/definitions/Brand'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /brands/:id/products:
    get:
      summary: Product listing for a specific ID
      description: |
        Returns data for a specific product.
      parameters:
        - name: productId
          in: query
          description: ProductId
          required: true
          type: number
          format: integer
      tags:
        - ProductId
      responses:
        '200':
          description: An object 
          schema:
            type: object
            items:
              $ref: '#/definitions/ProductId'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /me:
    get:
      summary: User Profile
      description: >-
        The User Profile endpoint returns information about the user that
        has authorized with the application.
      tags:
        - User
      responses:
        '200':
          description: Profile information for a user
          schema:
            $ref: '#/definitions/Profile'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Product:
    type: object
    properties:
      product_id:
        type: string
        description: >-
          Unique identifier representing a specific product for a given latitude
          & longitude. For example, uberX in San Francisco will have a different
          product_id than uberX in Los Angeles.
      description:
        type: string
        description: Description of product.
      display_name:
        type: string
        description: Display name of product.
      capacity:
        type: string
        description: 'Capacity of product. For example, 4 people.'
      image:
        type: string
        description: Image URL representing the product.
  Brand:
    type: object
    properties:
      product_id:
        type: string
        description: >-
          Unique identifier representing a specific product for a given latitude
          & longitude. For example, uberX in San Francisco will have a different
          product_id than uberX in Los Angeles
      currency_code:
        type: string
        description: '[ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency code.'
      display_name:
        type: string
        description: Display name of product.
      estimate:
        type: string
        description: >-
          Formatted string of estimate in local currency of the start location.
          Estimate could be a range, a single number (flat rate) or "Metered"
          for TAXI.
      low_estimate:
        type: number
        description: Lower bound of the estimated price.
      high_estimate:
        type: number
        description: Upper bound of the estimated price.
      surge_multiplier:
        type: number
        description: >-
          Expected surge multiplier. Surge is active if surge_multiplier is
          greater than 1. Price estimate already factors in the surge
          multiplier.
  Profile:
    type: object
    properties:
      first_name:
        type: string
        description: First name of the Uber user.
      last_name:
        type: string
        description: Last name of the Uber user.
      email:
        type: string
        description: Email address of the Uber user
      picture:
        type: string
        description: Image URL of the Uber user.
      promo_code:
        type: string
        description: Promo code of the Uber user.
  ProductId:
    type: object
    properties:
      uuid:
        type: string
        description: Unique identifier for the activity
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
