swagger: "2.0"
info:
  title: Sunglasses API
  description: an API for a sunglasses web page
  version: 1.0.0
tags:
  - name: "Sunglasses"
    description: "Get information about sunglasses available"
  - name: "user"
    description: "Information about the current user"
  - name: "store"
    description: "State of the shopping session"
paths: 
  /sunglasses/sunglasses-search:
    get:
      responses:
        '200':
          description: "A list of sunglasses"
        '400':
          description: "Search parameter must be a string"
      parameters:
        - in: query
          name: search-query
          type: string
      tags:
        - "Sunglasses"
  /user/login:
    get:
      responses:
        '200':
          description: "user is now logged in"
        '400':
          description: "incorrect username or password"
      
 
   
      
        
