swagger: "2.0"
info:
  title: Sunglasses.io API
  description: An API to support the Sunglasses.io platform
  version: 1.0.0
paths:
  /api/brands:
    get:
      summary: Brands
      description: |
        The Brands endpoint allows you to retrieve the brands.
